--Example data autogenerated using ChatGPT

INSERT IGNORE INTO tasks (id, task_name, date_target, notes, status) VALUES
    (1, 'Complete project proposal', 'October 15', 'Review and finalize the project proposal', 'incomplete'),
    (2, 'Prepare for client meeting', 'October 18', 'Gather necessary documents and presentations', 'incomplete'),
    (3, 'Code refactoring', 'October 20', 'Refactor the existing codebase for better maintainability', 'incomplete'),
    (4, 'Write unit tests', 'October 22', 'Create unit tests to ensure code reliability', 'incomplete'),
    (5, 'Design database schema', 'October 25', 'Define the structure of the application database', 'incomplete'),
    (6, 'Implement user authentication', 'October 28', 'Integrate user authentication functionality', 'incomplete'),
    (7, 'Deploy to staging environment', 'October 30', 'Prepare and deploy the application to the staging environment', 'incomplete'),
    (8, 'Write API documentation', 'November 2', 'Document the API endpoints and usage', 'incomplete'),
    (9, 'Conduct usability testing', 'November 5', 'Gather feedback on the user interface and experience', 'incomplete');
