--Example data autogenerated using ChatGPT

INSERT IGNORE INTO tasks (id, task_name, notes, status) VALUES
    (1, 'Complete project proposal', 'Review and finalize the project proposal', 'incomplete'),
    (2, 'Prepare for client meeting', 'Gather necessary documents and presentations', 'incomplete'),
    (3, 'Code refactoring', 'Refactor the existing codebase for better maintainability', 'incomplete'),
    (4, 'Write unit tests',  'Create unit tests to ensure code reliability', 'incomplete'),
    (5, 'Design database schema', 'Define the structure of the application database', 'incomplete'),
    (6, 'Implement user authentication', 'Integrate user authentication functionality', 'incomplete'),
    (7, 'Deploy to staging environment', 'Prepare and deploy the application to the staging environment', 'incomplete'),
    (8, 'Write API documentation', 'Document the API endpoints and usage', 'incomplete'),
    (9, 'Conduct usability testing', 'Gather feedback on the user interface and experience', 'incomplete');
